'use strict';
// const uuid = require('uuid');

// console.log('hello freind');
// console.log('Unique id generated by uuid: ', uuid.v4());

// const clients = ["Mango", "Ajax", "Poly"];
// let i = 0;

// while (i < clients.length) {
//   console.log('Logging clients: ', clients[i]);
//   i += 1;
// }


// const numbers = [];
// let num = 0;

// while (num < 10) {
//   numbers.push(num);
//   num += 1;
// }

// console.log("numbers: ", numbers);

//=============================================
// Итераторы по традиции называются буквами i/j/k
// const number = 11;

// for(let i = 0; i < number; i += 1) {
//   console.log(i);
// }

//=============================================
// Вспомним про операцию a % b и выведем остаток
// от деления используя цикл
// for(let i = 0, max = 10; i < max; i += 1) {
//     console.log(`${max} % ${i} = `, max % i);
//   }

//=============================================
// const clients = ['Mango', 'Ajax', 'Poly'];

// for(let i = 0, max = clients.length; i < max; i += 1) {
//   console.log(clients[i]);
// }

//=============================================
// const numbers = [];

// for(let i = 0; i < 10; i += 1) {
//   numbers.push(`number-${i}`);
// }

// console.log(numbers);

// let firstNumber;

/*
 * Переменные объявленые как const обязательно должны быть инициализированы
 * значением во время объявления, иначе будет ошибка
 */
// const secondNumber = 15;

/*
 * Значение переменной можно получить обратившись к ней по имени.
 * console.log() используется для вывода данных в консоль разработчика,
 * с этим методом более детально познакомимся позже.
 */
// console.log('secondNumber: ', secondNumber); // 15

// const isComing = confirm('Please confirm hotel reservation');
// console.log(isComing);

// const hotelName = prompt('Please enter desired hotel name:');
// alert(hotelName);

// const valueA = 5;
// console.log(typeof Number(valueA)); // 'number'
// console.log(Number(valueA)); // 5
// console.log(typeof (valueA)); // 'number'

console.log((0.1 * 10 + 0.2 * 10) / 10);
